### ISSUE TITLE
Defining any array constants causes input arrays to be rewritten

### ISSUE THREAD

**Issue by ericwong3** [gpujs/gpu.js#608] opened 2020-05-11 15:53 UTC
Might be related to #520 

## *What* is wrong?
When an array constant is defined, the kernel function messes up the variables, apparently the input variables itself is overwritten by the constant array.

## *Where* does it happen?
After running a GPU.js kernel and observing the output.

## *How* do we replicate the issue?
Use this code:
```js
const { GPU } = require('gpu.js');
const gpu = new GPU();
const naiveFn = gpu.createKernel(function(a, b) {
    return a[this.thread.y][this.thread.x];
    // return b[this.thread.y][this.thread.x];
}, {
  constants: {
    // zzz: [21,23],
  }
}).setOutput([2, 2]);

const c = naiveFn([[2,3], [5,7]], [[11,13],[17,19]]);
console.log(c);
```
A very simple function that just returns the input array.

When this is executed, the result is normal, i.e.: 

`[ Float32Array [ 2, 3 ], Float32Array [ 5, 7 ] ]` when `return a` line is active, and 
`[ Float32Array [ 11, 13 ], Float32Array [ 17, 19 ] ]` when `return b` line is active.

However, if I uncomment the constants property in settings object, which defines an array zzz, the output becomes:

`[ Float32Array [ 21, 23 ], Float32Array [ 0, 0 ] ]` when `return a` line is active, and 
`[ Float32Array [ 2, 3 ], Float32Array [ 5, 7 ] ]` when `return b` line is active.

As you can see, `b` in the kernel now holds the first input array, and `a` in kernel becomes the array defined in `constants.zzz`.

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
The array constant definition should not affect the parameters, and the correct result (i.e. the first one) should be returned regardless.

**Comment by y4nnick** [comment] 2020-06-20 09:31
Any update on this?
It gets even worse when the constants array has not the same size as the inputs, because than a ` Error: too many arguments for kernel` is raised.

By debugging i found out that the `args` in the `setupArguments` function are indeed the constants and not the arguments of the kernel!

**Comment by tonyg** [comment] 2020-12-02 09:44
Successfully reproduced the fault with node 12.19.1, gpu.js 2.10.5.

**Comment by HarshKhandeparkar** [comment] 2020-12-02 10:47
Interesting.... I was seeing weird things in another unrelated project but I had no idea what was happening... Maybe this was happening. Really waiting for a fix :smiley:

**Comment by robertleeplummerjr** [comment] 2020-12-02 13:50
Looking at it now.

**Comment by robertleeplummerjr** [comment] 2020-12-02 19:42
Found the issue, will have a PR up today or tomorrow with a unit test preventing regressions.

**Comment by robertleeplummerjr** [comment] 2020-12-03 15:51
Fixed in https://github.com/gpujs/gpu.js/pull/651 and released in https://www.npmjs.com/package/gpu.js/v/2.10.6

**Comment by robertleeplummerjr** [comment] 2020-12-03 15:52
Unit tests: https://github.com/gpujs/gpu.js/pull/651/files#diff-b8e0cfe65cc2ec1a0acd99cbda3f767d05ec54ec8efdaaff0e130917998ef7bcR1

**Closed by robertleeplummerjr** 2020-12-03 15:51 UTC
