### ISSUE TITLE
4 + 4 = 16 ?

### ISSUE THREAD

**Issue by mad1ost** [gpujs/gpu.js#422] opened 2019-02-13 09:14 UTC
```
const gpu = new GPU();
var myFunc = gpu.createKernel(function(a, b) {
    return a[this.thread.x] + b[this.thread.x];
}).setOutput([10]);
console.log(myFunc([0,1,2,3,4,5,6,7,8,9], [0,1,2,3,4,5,6,7,8,9]));
Float32Array(10) [0, 1.9999998807907104, 4, 5.999999523162842, 15.999999046325684, 15.999999046325684, 15.999999046325684, 15.999999046325684, 15.999999046325684, 15.999999046325684]
```
If use this code with files from `https://github.com/abhisheksoni27/gpu.js-demo` (using setDimensions instead setOutput) or in `http://gpu.rocks/playground` the result will be
```
Float32Array(10) [0, 1.9999998807907104, 4, 5.999999523162842, 15.999999046325684, 10, 12, 14, 16, 17.999998092651367]
```
but also 4 + 4 = 16

**Comment by mad1ost** [comment] 2019-02-14 20:54
It seems that there is problem with `Intel(R) Core(TM) i5 CPU M 450 @ 2.40GHz` and his 
`Intel® HD Graphics`. With another CPU or GPU all ok.

**Comment by robertleeplummerjr** [comment] 2019-02-14 21:57
Could you upgrade to a later version of gpu.js?  Say https://www.npmjs.com/package/gpu.js/v/1.10.4?

**Comment by mad1ost** [comment] 2019-02-15 06:03
The first code was obtained using gpu-browser.js version `2.0.0-rc.1`

**Comment by mad1ost** [comment] 2019-02-15 06:05
The first code was obtained using `gpu-browser.js` version `2.0.0-rc.1`

**Comment by robertleeplummerjr** [comment] 2019-02-25 13:04
Was this with node or web?

**Comment by mad1ost** [comment] 2019-03-05 16:30
Web

**Comment by robertleeplummerjr** [comment] 2019-05-17 13:35
Can you try with the latest v2 rc13 and see if this is still an issue?

**Comment by HarshKhandeparkar** [comment] 2019-05-17 14:05
Maybe this is some weird precision error. Try multiplying and dividing by `100` or `10`

**Comment by HarshKhandeparkar** [comment] 2019-05-17 14:07
Another thing, why do you have `[this.thread.x]` inside both `a[]` and `b[]`?

**Comment by HarshKhandeparkar** [comment] 2019-05-17 14:08
Also you can try debugging by just returning `this.thread.x + this.thread.y`

**Comment by HarshKhandeparkar** [comment] 2019-05-17 14:09
Oh sorry, the output size is 1d.

**Comment by mad1ost** [comment] 2019-05-18 09:37
Yes, now it's ok, but with 2 warnings
```
const gpu = new GPU();
var myFunc = gpu.createKernel(function(a, b) {
    return a[this.thread.x] + b[this.thread.x];
}).setOutput([10]);
console.log(myFunc([0,1,2,3,4,5,6,7,8,9], [0,1,2,3,4,5,6,7,8,9]));
gpu-browser.js.1:10767 WebGL: INVALID_VALUE: enableVertexAttribArray: index out of range
build @ gpu-browser.js.1:10767
run @ gpu-browser.js.1:10804
getIsFloatRead @ gpu-browser.js.1:7604
getFeatures @ gpu-browser.js.1:10420
setupFeatureChecks @ gpu-browser.js.1:10407
get isSupported @ gpu-browser.js.1:10387
chooseKernel @ gpu-browser.js.1:13754
GPU @ gpu-browser.js.1:13701
(anonymous) @ VM66:1
gpu-browser.js.1:10768 WebGL: INVALID_VALUE: vertexAttribPointer: index out of range
build @ gpu-browser.js.1:10768
run @ gpu-browser.js.1:10804
getIsFloatRead @ gpu-browser.js.1:7604
getFeatures @ gpu-browser.js.1:10420
setupFeatureChecks @ gpu-browser.js.1:10407
get isSupported @ gpu-browser.js.1:10387
chooseKernel @ gpu-browser.js.1:13754
GPU @ gpu-browser.js.1:13701
(anonymous) @ VM66:1
VM66:5 Float32Array(10) [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
```

**Comment by robertleeplummerjr** [comment] 2019-05-18 18:55
I added this test, and cannot reproduce:
```js
const { assert, skip, test, module: describe } = require('qunit');
const { GPU } = require('../../src');

describe('issues #422 - warnings');

function warnings(mode) {
  const gpu = new GPU({ mode });
  const kernel = gpu.createKernel(function(a, b) {
    return a[this.thread.x] + b[this.thread.x];
  }).setOutput([10]);
  assert.deepEqual(Array.from(kernel([0,1,2,3,4,5,6,7,8,9], [0,1,2,3,4,5,6,7,8,9])), [0,2,4,6,8,10,12,14,16,18]);
  gpu.destroy();
}

test('auto', () => {
  warnings();
});

test('gpu', () => {
  warnings('gpu');
});

(GPU.isWebGLSupported ? test : skip)('webgl', () => {
  warnings('webgl');
});

(GPU.isWebGL2Supported ? test : skip)('webgl2', () => {
  warnings('webgl2');
});

(GPU.isHeadlessGLSupported ? test : skip)('headlessgl', () => {
  warnings('headlessgl');
});

test('cpu', () => {
  warnings('cpu');
});
```

This will be released in a few days.

**Comment by robertleeplummerjr** [comment] 2019-05-18 18:55
I'll go ahead and have this unit test added to the project.

**Comment by robertleeplummerjr** [comment] 2019-05-27 15:37
Closing, will be releasing this fix soon.

**Closed by robertleeplummerjr** 2019-05-27 15:37 UTC
