### ISSUE TITLE
Problem with forwarding calculations to GPU

### ISSUE THREAD

**Issue by ziogibom** [gpujs/gpu.js#242] opened 2018-01-11 14:33 UTC
I am trying to do some calculations using GPU, maybe I am missing some basics. Below You can find my code below.
Any ideas?

```
const gpu = new GPU({mode: 'webgl'});
var elasticModel =[]
var maxPsoBird=[];
var minPsoBird=[];
const kernel = gpu.createKernel(function(elasticModel) {
    var c = 2172.479446498065
    var det = 0.0;
    var su = 0.0;
    var sd = 0.0;
    var bu = 0.0;
    var A = 0.0;
    var B = 0.0;
    var o = 15.0;
    if (1.0 - ((c * c) / (elasticModel[this.thread.x][4] / elasticModel[this.thread.x][6])) < 0.0)  det = -1;
    sd = sqrt(1.0 - ((c * c) / (elasticModel[this.thread.x][4] / elasticModel[this.thread.x][6])));
    if (((c * c) / (elasticModel[this.thread.x][3] / elasticModel[this.thread.x][5])) - 1.0 < 0.0)  det = -1;
    su = sqrt(((c * c) / (elasticModel[this.thread.x][3] / elasticModel[this.thread.x][5])) - 1.0);
    if (c < 0.0) det =  -1;
    bu = (o / c) * su * elasticModel[this.thread.x][0];
    A = 2.0 * su * elasticModel[this.thread.x][3] * sin(bu);
    B = 2.0 * sd * elasticModel[this.thread.x][4] * cos(bu);
    if (det === 0.0) det = abs(A - B);
   
    return det;
}).setOutput([1000000]);
elasticModel[0] = [500.0, 19800000.0, 109850000.0, 8800000.0, 41600000.0, 2.2, 2.4]
for (j = 0; j < 7; j++) {
    maxPsoBird[j] = elasticModel[0][j] * 1.5;
    minPsoBird[j] = elasticModel[0][j] * 0.5;
}

for (i = 1; i < 1000000; i++) {
        elasticModel.push([500.0, 19800000.0, 109850000.0, 8800000.0, 41600000.0, 2.2, 2.4])
			for (j = 0; j < 7; j++) {
						elasticModel[i][j] = minPsoBird[j]+(maxPsoBird[j]-minPsoBird[j])*Math.random();
			}
        console.log(elasticModel[i]);
}


console.log(kernel(elasticModel));
```
```
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title></title>
    <script src='gpu-core.min.js'></script>
    <script src='gpu.min.js'></script>
    <script src="./gpu.js"></script>
	<script src="./gpu-tests.js"></script>
</head>

<body>
</body>

</html>
```

**Comment by robertleeplummerjr** [comment] 2019-02-25 12:58
I just used your version with [v2, rc2](https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc2), however, I shortened the value `1000000` to `10` for testing, and it worked fine as far as I could tell.

The only thing I could think of is that the value you are sending is quite large, maybe it needs broken up?  What is failing specifically?

Other recommendations:
* Please just use `const gpu = new GPU({ mode: 'gpu' });` and not the actual backend names.  Those are generally there for just testing.  The supported modes are "gpu", "cpu", and falsey.
* Please just include one gpu.js source in your html page.  Having many of them will have unintended consequences.

Closing as unable to clarify and reproduce for the time being, but will reopen to assist when reproduction steps can be had.

**Closed by robertleeplummerjr** 2019-02-25 12:58 UTC
