### ISSUE TITLE
Problems with retrieving array after read and write to same texture

### ISSUE THREAD

**Issue by jaapmurre** [gpujs/gpu.js#431] opened 2019-03-02 23:46 UTC
I am developing a neural network simulator where a each neuron in a group of neurons sends spikes to other neurons. My activation function accepts incoming spikes as an argument, with (synaptic) weights and then outputs spikes again if the weighed input is high enough. This can be made to work by setting the kernel function to 'mutable' (see #424). However, when after Z iterations, I convert the spike texture to an array, the time taken to do this is proportional to Z. Also, if I increase the number of weights, the conversion time increases proportionally, so I suspect it is a memory issue. 

Maybe, at each iteration, a new spike array is created in memory, or even a complete duplication of my weights (4 MB weights) and this may somehow (linearly) slow down the conversion process. I also tried to alternate between two spike arrays kept as textures (in a kernelmap) and alternate: reading from one and writing to the other. This works well, but with identical conversion problems. I also tried the same with alternating two different kernel functions; same thing. Also, tried various settings of the 'mutable' property. 

The iterations themselves run superfast (compared to CPU) but the increasingly slow conversion is a real problem. (I am running gpu.js 2.0.0.rc2 on a GTX 680 with 1500+ CUDA cores on Chrome on Windows 10.)

Is there a way to remedy this? Did I miss something?

**This is the code file I used for the most basic test:**

**issue_code_minimal.js**

    // Make sure the data remains at the gpu as a texture
    function texturizeInputData1D(value,gpu) 
    { 
        if (gpu.mode === 'cpu') {
            return value;
        }

        const f = gpu.createKernel(function (val) 
        {
            return val[this.thread.x];
        }, 
        {
            output: [value.length],
            pipeline: true,
            mutable: true
        });

        return f(Array.from(value));
    }

    // Make sure the data remains at the gpu as a texture
    function texturizeInputData2D(value,gpu) 
    { 
        if (gpu.mode === 'cpu') {
            return value;
        }

        const f = gpu.createKernel(function (val) 
        {
            return val[this.thread.y][this.thread.x]; // Watch out: GPU uses inverted matrix storage
        }, 
        {
            output: [value[0].length,value.length], // Watch out: GPU uses inverted matrix storage
            pipeline: true,
            mutable: true
        });

        return f(Array.from(value));
    }

    const textureToArray = function(texture,gpu) 
    {
        if (gpu.mode === 'cpu') {
            return texture;
        }

        const f = gpu.createKernel(function(tx) 
        {
            return tx[this.thread.y][this.thread.x]; // Watch out: GPU uses inverted matrix storage
        }).setOutput(texture.output);

        return f(texture);
    }

    // Generate a simple example network
    function generateSimpleNN(size,insize) 
    {
        var spikes = new Float32Array(size); // Create an array and fill with 1s; spike = binary activation 
        spikes.fill(1);

        var innodes = [];
        var inweights = [];

        for (let i = 0; i < size; i++) {
            innodes[i] = new Float32Array(insize);
            inweights[i] = new Float32Array(insize);

            for (let j = 0; j < insize; j++) { // Dummy incoming weights and in-node indices (= innodes)
                innodes[i][j] = j; // j-th innode has node index j
                inweights[i][j] = j*0.1; // Dummy, nonsense weight
            }
        }

        return {spikes: spikes, innodes: innodes, inweights: inweights};
    }

    const duration = 8;    // Number of ms to simulate; increasing this, increases the textureToArray() conversion in line 111
    const size = 1024*4;    // Number of neurons
    const insize = 1024;    // Number of incoming connections per neuron; 8*1024*1024 seems to be upper limit of number of weights on GPU
    const nn = generateSimpleNN(size,insize);

    const gpu = new GPU();

    const calcActGPU = gpu.createKernel(function(spikes,innodes,inweights) {
        let net = 0;
        let x  = this.thread.x;
        for (let j = 0; j < this.constants.insize; j++) {
            net += inweights[x][j] * spikes[innodes[x][j]];
        }
        return net > 0 ? 1 : 0;
    },
    {
        constants: { "insize": insize },
        pipeline: true,
        immutable: true, // With false this does not seem to work correctly; with true it seems to assign a lot of memory each iteration
        output: [size]
    });

    let spikes = texturizeInputData1D(nn.spikes,gpu);
    let innodes = texturizeInputData2D(nn.innodes,gpu);
    let inweights = texturizeInputData2D(nn.inweights,gpu);

    let t1 = performance.now();
    for (let k = 0; k < duration; k++) {
        spikes = calcActGPU(spikes,innodes,inweights);
    }
    console.log("GPU: ",performance.now()-t1," ms");
    t1 = performance.now();
    console.log("Result GPU: ",textureToArray(spikes,gpu));
    console.log("Retrieving results from texture: ",performance.now()-t1," ms");

    gpu.destroy();

**Using the following file to run the above:**

    <!DOCTYPE html>
    <html lang='en'><head>
        <title>Issue Code Index</title>
    </head><body>
        <script src='gpu.js/bin/gpu-browser-core.min.js'></script>
        <script src='gpu.js/bin/gpu-browser.min.js'></script>
        <script src='issue_code_minimal.js'></script>
    </body></html>

**Comment by robertleeplummerjr** [comment] 2019-03-04 15:47
Likely the issue is when you actually need the output of the neural network.  Two things contribute to things being very slow when coordinating efforts from GPU to CPU:

* Calls to [gl.readPixels()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels) (which is equivalent to a non pipeline kernel, returning a value)
  * a reason this is very slow is you are asking ALL GPU processes to synchronize and stop.  This is extremely time expensive, because you are asking something highly synchronous to synchronize and stop.
   * a reason this is resource intensive is you are asking to copy everything that exists on the GPU for a referenced output to be copied to the CPU.  These are physically two different chips with two different locations on the motherboard, there is time lost in transit as well.


There may be something we've missed that contributes to slowness as well, but a quick means of resolving this is asking: do I really need the value back from the GPU?

Ways to "skirt" the issue:
* When training a neural network, ask for the value _every once in a while_ but not on every time.  This has helped me in most cases.  Rather than read every time, for example for error checking and logging, do it every 100th, or 1000th time.  This isn't ideal in all scenarios.
* Perhaps logging the value form the GPU to the GPU?  This isn't yet something we've fulfilled a feature for, but it has been suggested to simply log the value from the GPU to the monitor, which would be like this: https://github.com/gpujs/gpu.js/issues/240.  In other words, a `console.log()` for the GPU.  While this feature has not been yet built, it'd be of interest to me, and many others.

**Comment by jaapmurre** [comment] 2019-03-04 17:31
Thanks for your comments! I think I am already doing your first solution in the included script: I am running in texture-only mode for a longish time (called 'duration' in the script). In practice: If I run for 40 iterations without converting my spikes to Array, then it takes me roughly 1000 ms to retrieve my spikes (convert to Array). This slow conversion takes away my speed increase vs CPU. 

Worse is that, if I now run for 80 iterations instead of 40, it takes 2000 ms to retrieve the same array, 160 takes 4000 ms etc. I have taken great care to leave everything in textures while running (and preload into textures). But at some point I want to see the result (here 'spikes' in Array format). The longer I run, however, the longer the conversion takes, which seems odd and makes implementation op GPU inefficient and unusable.

I am assuming all textures are constantly being reused at the GPU but this does not seem to be the case. Perhaps, my implementation is still flawed but I tried many variations. For example, I also used a flip or pingpong technique, which worked fine but with the same linear increase in retrieval time. This time can increase to over one minute or longer when I run the network for 1000 iterations (without converting anything to Array), while the retrieved data is still an array of 4*1024 elements.

I take your point that I can log to the screen but this would not solve my problem. It is not a matter of intermittent logging, which I live without, but of retrieving final results.

**Comment by robertleeplummerjr** [comment] 2019-03-04 18:36
>Thanks for your comments!

Ty for reading them!  I also feel that:
1. There are things that can be written better in gpu.js, to better facilitate speed.
2. There may be bugs.
3. Likely not all paths have been explored for creatively solving directly, or indirectly, this issue.

I welcome more research or scrutiny of any solution, and would really love to solve this issue once and for all.

**Comment by robertleeplummerjr** [comment] 2019-03-04 18:36
Have you ran a profiler on your code to see where, line by line, bottlenecks are?

**Comment by robertleeplummerjr** [comment] 2019-05-21 13:59
I saw this: 
```js
return f(Array.from(value));
```

Why are you turning the input into an array every time?  A kernel can take a texture just fine.  This may be part of the issue here.

**Comment by robertleeplummerjr** [comment] 2019-05-22 12:47
Another thing to try, when using something that is displayed that is visual, make sure you use the browser's [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame), and render there, rather than setting your own interval.

The other thing is to ensure you use `pipeline: true` mode if at all possible, and do not convert the output of those kernels to an array, rather keep it as a texture.  This will keep as much work (CPU and Memory) on the GPU as possible, and only use `output.toArray()` where absolutely needed.

Going to go ahead and close as I do not currently see this as actionable.  May need more insight if the developer intends on collaborating.

**Closed by robertleeplummerjr** 2019-05-22 12:47 UTC
