### ISSUE TITLE
output RGBA to texture and input that to next kernel

### ISSUE THREAD

**Issue by Easonzero** [gpujs/gpu.js#326] opened 2018-06-25 05:44 UTC
hello, i can't output RGBA data to the texture,and input to next kernel like an image. 

I hope to input a array and convert the array to RGBA by this.color. but when i do so, the texture which i get can't be input to kernel like an image, and get RGBA from this texture in kernel . in fact, its type is array of float, please ask me how to do this ?

**Comment by Easonzero** [comment] 2018-06-27 13:51
i implement it to load image of canvas into the next kernel by the Promise, and my project is ![FunctionalImaged](https://github.com/Easonzero/FunctionalImage).

**Comment by robertleeplummerjr** [comment] 2018-06-27 13:57
I think is partially a duplicate of https://github.com/gpujs/gpu.js/issues/310
Some things that are needed are feedback on the proposal, and then action.  If you could help with either, or both, we can get this finalized and part of gpu.js.

**Comment by robertleeplummerjr** [comment] 2018-06-27 14:05
Also, cool project!

**Comment by Easonzero** [comment] 2018-06-28 03:12
thanks, looking forward to the update of gpu.js

**Closed** 2018-06-28 03:13 UTC
