### ISSUE TITLE
Other language features?

### ISSUE THREAD

**Issue by sawman** [gpujs/gpu.js#39] opened 2016-04-29 07:16 UTC
Are there any other JS language features that we want to support?

**Comment by YIbanYiban** [comment] 2017-06-21 06:54
hoping for the support for key-value structure.

**Comment by robertleeplummerjr** [comment] 2017-06-21 11:44
I _think_ that is being added here: https://github.com/gpujs/gpu.js/issues/84

**Comment by robertleeplummerjr** [comment] 2019-04-26 03:05
>hoping for the support for key-value structure.

This was added in v1, but the issue is very open ended.  Closing for time being as too open ended.  However if there are recommendations, wouldn't mind creating a new issue for.

**Closed by robertleeplummerjr** 2019-04-26 03:05 UTC
Labels: question, v1
