### ISSUE TITLE
Add support for custom GLSL-level functions

### ISSUE THREAD

**Issue by Ameobea** [gpujs/gpu.js#171] opened 2017-08-24 02:22 UTC
Although the JavaScript translation is excellent, I'm coming across situations where I'd like to make use of GLSL-level functions that aren't available in pure JavaScript without writing them manually. 
 For example, the GLSL `mix()` function isn't currently accessible from within user kernel functions.

I propose the addition of a system for accessing native GLSL functions from within use kernel functions.  Perhaps an object could be added to the kernel function's context like `this.native.mix(a, b, w)` that would translate directly to the GLSL level `mix()` being inserted.

Another possible useful addition would be to allow users to supply GLSL functions as strings to be inserted into the header.  Something like this:
```js
gpu.addNativeFunction('myCustomfunction', `
  float myCustomFunction(x, y, z) {
    ...
  }
`);
```

That function would then be available for use within use kernel functions through something like `this.custom.myCustomfunction(1.0, 2.0, 3.0)`.  Using this method, specialized pieces of GLSL can be written to accommodate individual needs without dropping down entirely into GLSL.

I'd love to hear some feedback for this idea.  I really think it would be a useful addition to the library (I have a use case it would help myself) and would go far to improve the flexibility of the library as a whole.

**Comment by robertleeplummerjr** [comment] 2017-08-28 12:35
I believe this is a semi-duplicate of: https://github.com/gpujs/gpu.js/issues/62

**Comment by robertleeplummerjr** [comment] 2017-08-28 12:51
I _really_ like the name mentioned here: `addNativeFunction`, and will be changing `addGLSLFunction` to it, as it is a brand new feature, and the method name is reusable.

**Comment by robertleeplummerjr** [comment] 2017-08-28 13:11
Added: https://github.com/gpujs/gpu.js/commit/49c8af0a4478049cdf6e62b0eeb319d5fe499884

**Closed by robertleeplummerjr** 2017-08-28 13:11 UTC
