### ISSUE TITLE
Errors with very large arrays

### ISSUE THREAD

**Issue by ArnaudBienner** [gpujs/gpu.js#64] opened 2017-04-18 21:09 UTC
Hi,

When trying to execute a GPU function on a large array (1920x1080x3 which represents a 1920x1080 picture with 3 color components) it fails with the following error:
"RangeError: too many arguments provided for a function call" on Firefox
"RangeError: Maximum call stack size exceeded" on Chrome.

See attached example, which do has non-op function to exhibit the issue: https://drive.google.com/file/d/0BxAjgoe3PaRwaTFHMUsxWG1xV2c/view?usp=sharing
It works when working on smaller arrays, but fails on large ones.

I'm not sure how big arrays are common in Javascript (I feel like Firefox or Chrome have issues handling them anyway) but such arrays don't sound that big to me, particularly for taking full advantage of GPU operations by working on big data set.

**Comment by robertleeplummerjr** [comment] 2017-04-19 01:58
Thank you for providing so much detail in one run!  The problem is the ecmascript parser in this scenario.  I'm working on some refactors (lib owners, feel free to shoot down), that I hope will fix this problem.  An easy fix would be to not use concat in the parser.

**Comment by robertleeplummerjr** [comment] 2017-04-19 16:11
Further, I've discovered that actually isn't the problem.  I'll submit a fix for this soon.

**Comment by ArnaudBienner** [comment] 2017-04-19 16:16
@robertleeplummerjr Awesome! Thanks a lot for your reactivity :)
I'm looking forward for your fix and would be happy to test it once available ;)

**Comment by robertleeplummerjr** [comment] 2017-04-19 16:31
If you replace the flatten function with this: ```js
function flatten(arr) {
        var result = [];
        var i;
        var j;

        if (GPUUtils.isArray(arr[0])) {
          if (GPUUtils.isArray(arr[0][0])) {
            if (Array.isArray(arr[0][0])) {
              for (i = 0; i < arr.length; i++) {
                var nestedArray = arr[i];
                for (j = 0; j < nestedArray.length; j++) {
                  result.push.apply(result, nestedArray[j]);
                }
              }
            } else {
              for (i = 0; i < arr.length; i++) {
                result.push.apply(result, arr[j]);
              }
            }
          } else {
            result.push.apply(result, arr);
          }
        } else {
          result = arr;
        }
        return result;
      }
```

You should get something usable.  I've put the whole pretty-printed file here: https://gist.github.com/robertleeplummerjr/f49e83e95c16543bc8028b4209e9e2fd for convenience.

**Comment by ArnaudBienner** [comment] 2017-04-20 08:48
@robertleeplummerjr Amazing! I gave your version a quick try and it is working really great! Thanks again for this!
Did you tried to submit a pull request to get this integrated within the main repository? I think this fix could be useful to many people.

**Comment by robertleeplummerjr** [comment] 2017-04-20 15:14
Yup ^

**Closed** 2017-05-07 10:49 UTC
