### ISSUE TITLE
Error:  Auto Dimensions Only Supported for Kernels with only One Input.

### ISSUE THREAD

**Issue by soundnerd** [gpujs/gpu.js#183] opened 2017-09-07 16:35 UTC
Hello,

I am getting an error from gpu.js that I don't seem to understand:  Auto Dimensions only supported for Kernels with only one input.  Below is the JavaScript that I am trying to run:

const gpu = new GPU();
            const opt = {
                        output: [512, 512],
                        graphical: true
                        }
            const amplitude_to_density = gpu.createKernel(function(rasters) {
                // function amplitude_to_density(){
                var mag = [];
                var sum =0;
                for (var i=0; i < rasters[0].length; i++){
                    
                    var a = rasters[0][i]*rasters[0][i];
                    var b = rasters[1][i]*rasters[1][i];
                    mag.push(Math.max(Math.sqrt(a+b), .00001));
                    sum += mag[i];
                    }
                var data_mean = sum / mag.length;
                var cl = 0.8 * data_mean;
                var ch = 40 * cl;
                var m = (255 - 30)/Math.log10(ch/cl);
                var c = 30 - (m * Math.log10(cl));
                var output = [];
                for (var i=0; i < mag.length; i++){
                    output.push(Math.round((m * Math.log10(mag[i])) + c));
                    } 
                return output;
                }, opt);

Can you tell me what I am doing wrong please?  Thanks.

Daniel Haverporth

**Comment by RationalCoding** [comment] 2017-09-07 16:39
Duplicate of #177

**Comment by robertleeplummerjr** [comment] 2017-09-07 16:54
This was a bug, can you pull latest and see if that resolves it?  Likely if that doesn't we just need to run a build script if you are using the bin files.

**Comment by soundnerd** [comment] 2017-09-07 17:25
When I try to use the .setOutput() option I get an error message saying .setOutput() is not a function.  I downloaded the code yesterday from gpu.rocks from the Download (develop branch) option.  I installed it also from npm install gpu.js --save yesterday as well.  Should I run an npm update?

**Comment by robertleeplummerjr** [comment] 2017-09-07 17:29
That explains it.  Use this: https://github.com/gpujs/gpu.js/blob/develop/bin/gpu.js

**Comment by robertleeplummerjr** [comment] 2017-09-07 17:29
We are going to be updating the site so that it references github and not have to manage added dependencies.

**Comment by soundnerd** [comment] 2017-09-07 19:00
Thanks that fixes that particular error.  Quick question does shader language support Math.log10?  It appears that it doesn't support Math.round().

**Comment by robertleeplummerjr** [comment] 2017-09-07 19:21
`Math.round` will come after v1.  We don't support log10 yet, but if you want to add it, it looks like an implementation would be:
`log10(x) = log(x) / log(10) = (1 / log(10)) * log(x)`
from https://stackoverflow.com/questions/14081024/opengl-using-a-logarithmic-coordinates-axis

**Closed by robertleeplummerjr** 2017-09-07 19:21 UTC
